### ISSUE TITLE
Add tags to the repo 

### ISSUE THREAD

**Issue by rchapin** [orcaman/concurrent-map#106]
Most go projects add tags at various points in the development so that consumers of libraries can guarantee that they are getting a specific version that they know works with their code.

This project looks interesting and I was going to use it, however the fact that every time I build I am pulling from master and just hoping that nothing has changed that makes it incompatible with my application is a deal-breaker for me.

Please consider adding tags for stable versions of the library.

**Comment by orcaman** [comment]
added, thanks!
https://github.com/orcaman/concurrent-map/releases/tag/v1.0.0

**Comment by rchapin** [comment]
Awesome!  Thanks very much!
