### ISSUE TITLE
SetIfAbsent: Support Lazy value

### ISSUE THREAD

**Issue by JadenTeng** [orcaman/concurrent-map#28]
Sometime get value is cost too many cpu. So we cache the value on a map.

So I want to change the SetIfAbsent like that:

```
func (m *ConcurrentMap) SetIfAbsent(key string, fn func() interface{}) bool {
    // Get map shard.
    shard := m.GetShard(key)
    shard.Lock()
    _, ok := shard.items[key]
    if !ok {
        shard.items[key] = fn()
    }
    shard.Unlock()
    return !ok
}
```

Would you mind give suggestions for me?

**Comment by eranchetz** [comment]
Hi @JadenTeng, your example looks good to me. 
You can easily implement this function in your code, this is why GetShard() function is public. 
Or, even better, 
If you want, you can create a pull request with a new function LazySetIfAbsent(...) and we will merge it to our project.

good luck,
let us know if you need any assitance.

**Comment by JadenTeng** [comment]
Hi @eranchetz 

Please Review [pull request](https://github.com/streamrail/concurrent-map/pull/29/files).
