### ISSUE TITLE
concurrent output is wrong and uncertain

### ISSUE THREAD

**Issue by LoYoPP** [orcaman/concurrent-map#43]
test code:
`
package main

import (
            "fmt"
            "github.com/streamrail/concurrent-map"
            "sync"
)
var m = cmap.New()

func fun(wg *sync.WaitGroup) {
        v := 1
        if value, ok := m.Get("key"); ok {
            v += value.(int)
        }
        m.Set("key",v)
        wg.Done()
}

func main(){
        var wg sync.WaitGroup
        for i := 0; i < 10; i++ {
            wg.Add(1)
            go fun(&wg)
        }
        wg.Wait()
        fmt.Println(m.Get("key"))
}
`
output:

![image](https://cloud.githubusercontent.com/assets/3195838/18308173/006cbdc0-7526-11e6-8c77-b30cc7bf6be0.png)

**Comment by gmelika** [comment]
this is actually the correct behavior, and it has nothing to do with the library.  the function `fun` is not atomic, so the value of `key` is easily overwritten by an unexpected value.  if you want it to to behave the way you're expecting you have to wrap the following lines with a mutex

```
if value, ok := m.Get("key"); ok {
    v += value.(int)
}
m.Set("key",v)
```

**Comment by orcaman** [comment]
Thanks for contributing by having this discussion.
