### ISSUE TITLE
Returning from Iter() and IterBuffered() results in a deadlock

### ISSUE THREAD

**Issue by efeller** [orcaman/concurrent-map#50]
Hi all,

It looks like returning from Iter() and IterBuffered() before they have finished iterating results in a deadlock. Any idea of what is the suggested way to return properly (I would like to avoid looping through all elements)?

Example for deadlock:

for val := range yourmap.Iter() {
	data := val.Val...
	if  data == 10 {
		return true
	}
}

Thanks,
Eugen

**Comment by orcaman** [comment]
fix merged: https://github.com/orcaman/concurrent-map/pull/51
