### ISSUE TITLE
It is about memory consumption

### ISSUE THREAD

**Issue by pathbox** [orcaman/concurrent-map#53]
Hi, I use cmap in my app, I store 2w+  key-value in the cmp hash.
My app is go-socket.io, it maintains 1w+ socket connections
It probably make a big memory consumption ?  
Now my app consumes 14G memory
It is terrible, I am searching the problem

**Comment by orcaman** [comment]
Hi, what do you mean by "2w"? 

Did you try to profile your program or test with the native map?

The cmap memory footprint shouldn't be significantly larger than then the native one.

**Comment by pathbox** [comment]
Hi, yeah, you are right. The problem is not cmap. Today I read the source code from cmap, it is good
