### ISSUE TITLE
Golang 1.9 and concurrent map

### ISSUE THREAD

**Issue by matcornic** [orcaman/concurrent-map#60]
Hello, 

Thanks for this package that has been useful for years.
`Golang 1.9` now provides a [concurrent map](https://golang.org/pkg/sync/#Map) in standard library. Consider mentioning it on the `README` for those using latest version of Golang.

Though, the package is still very useful for older versions :)

**Comment by orcaman** [comment]
@matcornic thanks for the feedback, we're glad that you found this useful! 

As for the 1.9 sync.Map - it has a few key differences from this map. The stdlib sync.Map is designed for append-only scenarios. So if you want to use the map for something more like in-memory db, you might benefit from using our version. You can read more about it in the golang repo, for example here: https://github.com/golang/go/issues/21035#issuecomment-315584591 and here: https://stackoverflow.com/questions/11063473/map-with-concurrent-access

**Comment by matcornic** [comment]
@orcaman thanks for your quick answer ! Your explanation makes sense. So, in my opinion, differences between your package and standard library are worth explaining in the README.
We should be clear on which situation your library is more suited that the standard library, and in which cases it's not :+1:

**Comment by orcaman** [comment]
Good point. I will update the README.md

**Comment by orcaman** [comment]
Merged as per our discussion. Thanks!
