### ISSUE TITLE
Add possibility to conditionally remove elements 

### ISSUE THREAD

**Issue by colega** [orcaman/concurrent-map#61]
`Upsert` allows you te execute a callback, and depending on value update/set/insert a new one, but there's now way to atomically remove elements from the map depending on its values.

We have a small pub-sub implementation based on this map, each map element contains a slice of subscribers for a given topic (key). I don't see any way to remove a topic once everybody de-subscribed from it without accidentally removing new subscribers.

**Comment by orcaman** [comment]
PR merged
