### ISSUE TITLE
Why not having go routines in IterCB ?

### ISSUE THREAD

**Issue by a-lucas** [orcaman/concurrent-map#79]
The current implementation of iterCB is quite simple: 

```
// Callback based iterator, cheapest way to read
// all elements in a map.
func (m ConcurrentMap) IterCb(fn IterCb) {
	for idx := range m {
		shard := (m)[idx]
		shard.RLock()
		for key, value := range shard.items {
			fn(key, value)
		}
		shard.RUnlock()
	}
}
```

We could create `SHARD_COUNT` go routines , one for each shard, and do some parrallelism here.
If one callback function does lock the shard, that will keep the other ones unlocked.

Any specific reason why this is implemented this way ?

**Comment by a-lucas** [comment]
As a reply to my own question, 

I decided to quickly implement a solution and benchmark it: 

TLTR: it is because it is 2x faster .

```


func BenchmarkConcurrentMapOriginal(b *testing.B) {

	m := cmap.New()
	for i:=0; i<1000000; i++ {
		m.Set(strconv.Itoa(i), true)
	}

	b.ResetTimer()

	for i:=0; i<b.N; i++ {
		var count int64 =0
		m.IterCb(func(key string, val interface{}) {
			atomic.AddInt64(&count, 1)
		})
	}
}


func BenchmarkConcurrentMapModified(b *testing.B) {

	m := cmap.New()
	for i:=0; i<1000000; i++ {
		m.Set(strconv.Itoa(i), true)
	}

	b.ResetTimer()

	for i:=0; i<b.N; i++ {
		var count int64 =0
		m.IterConcurrentCb(func(key string, val interface{}) {
			atomic.AddInt64(&count, 1)
		})
	}
}


```
And the implementation:
```
func (m ConcurrentMap) IterConcurrentCb(fn IterCb) {
	var wg sync.WaitGroup

	wg.Add(len(m))
	for _, shard := range m {

		go func(shard *ConcurrentMapShared) {
			shard.RLock()
			for key, value := range shard.items {
				fn(key, value)
			}
			shard.RUnlock()
			wg.Done()
		}(shard)

	}
	wg.Wait()
}
```

**Comment by a-lucas** [comment]
So I come up with a new question:

Why is it slower? Shouldn't it be faster with concurrent access to shards?

**Comment by orcaman** [comment]
@a-lucas sometimes concurrency can actually slow you down. Once you fire up a goroutine, you rely on the go scheduler to execute those routines for you. This almost always makes sense when you have an I/O operation or a very heavy calculation going on. But for something that would get executed super fast on a CPU syncrhonous is the way to go. 

I have dedicated a post for this here, BTW: https://medium.com/@_orcaman/when-too-much-concurrency-slows-you-down-golang-9c144ca305a
