### ISSUE TITLE
len calculates each time in for loop

### ISSUE THREAD

**Issue by pavelblossom** [orcaman/concurrent-map#97]
in fnv32()... len will calculate each time.
It will be little but faster If we move it out of the loop 
`
func fnv32(key string) uint32 {
	hash := uint32(2166136261)
	const prime32 = uint32(16777619)
        keysLen := len(key)
	for i := 0; i < keysLen; i++ {
		hash *= prime32
		hash ^= uint32(key[i])
	}
	return hash
}
`

**Comment by orcaman** [comment]
Thanks! You're right. Solved [here](https://github.com/orcaman/concurrent-map/pull/98)
