### ISSUE TITLE
map.Items block indifinetly. 

### ISSUE THREAD

**Issue by dreson4** [orcaman/concurrent-map#99]
If you declare a concurrentMap item without creating it with `New()` then calling map.Items blocks forever.
```
        var work cmap.ConcurrentMap
	for k, _ := range work.Items() {
		fmt.Println(k)
	}
        //Never reached
```

I think this should be treated as a bug, it should panic just like how other methods panic when the map hasn't been created.

**Comment by orcaman** [comment]
I agree. Feel like submitting a PR for this? :-)

**Comment by dreson4** [comment]
Sent a PR for this.
https://github.com/orcaman/concurrent-map/pull/105

**Comment by orcaman** [comment]
PR Merged. Thanks!
